package trycatch

import javaemul.lang.*
import kotlin.jvm.*

open class TryCatch {
 open fun testMultiCatch() {
  try {
   throw kotlin.ClassCastException()
  } catch (e: kotlin.NullPointerException) {
   throw e!!
  } catch (e: kotlin.ClassCastException) {
   throw e!!
  } catch (r: kotlin.RuntimeException) {
   var r_1: kotlin.RuntimeException? = r
   r_1 = null
  }
 }

 open fun testEmptyThrowableCatch() {
  try {
   throw kotlin.ClassCastException()
  } catch (e: kotlin.Throwable) {}
  try {
   throw kotlin.ClassCastException()
  } catch (e_1: kotlin.Exception) {} catch (e_2: kotlin.Throwable) {}
 }

 open fun testEmptyThrowableRethrow() {
  try {
   throw kotlin.ClassCastException()
  } catch (e: kotlin.Throwable) {
   throw e!!
  }
 }

 open fun testFinally() {
  try {
   assert(true)
  } finally {}
 }

 open fun testTryWithResource() {
  try {
   var `$primaryExc`: kotlin.Throwable? = null
   var thing: trycatch.TryCatch.ClosableThing? = null
   var thing2: trycatch.TryCatch.ClosableThing? = null
   try {
    thing = trycatch.TryCatch.ClosableThing()
    thing2 = trycatch.TryCatch.ClosableThing()
    throw kotlin.Exception()
   } catch (`$exceptionFromTry`: kotlin.Throwable) {
    `$primaryExc` = `$exceptionFromTry`
    throw `$exceptionFromTry`!!
   } finally {
    `$primaryExc` = javaemul.internal.Exceptions.safeClose(thing2, `$primaryExc`)
    `$primaryExc` = javaemul.internal.Exceptions.safeClose(thing, `$primaryExc`)
    if (`$primaryExc` !== null) throw `$primaryExc`!!
   }
  } catch (e: kotlin.Exception) {}
 }

 open fun testTryWithResourceJava9() {
  val thing: trycatch.TryCatch.ClosableThing? = trycatch.TryCatch.ClosableThing()
  val thing2: trycatch.TryCatch.ClosableThing? = trycatch.TryCatch.ClosableThing()
  try {
   var `$primaryExc`: kotlin.Throwable? = null
   var `$resource`: trycatch.TryCatch.ClosableThing? = null
   var `$resource_1`: trycatch.TryCatch.ClosableThing? = null
   try {
    `$resource` = thing
    `$resource_1` = thing2
    throw kotlin.Exception()
   } catch (`$exceptionFromTry`: kotlin.Throwable) {
    `$primaryExc` = `$exceptionFromTry`
    throw `$exceptionFromTry`!!
   } finally {
    `$primaryExc` = javaemul.internal.Exceptions.safeClose(`$resource_1`, `$primaryExc`)
    `$primaryExc` = javaemul.internal.Exceptions.safeClose(`$resource`, `$primaryExc`)
    if (`$primaryExc` !== null) throw `$primaryExc`!!
   }
  } catch (e: kotlin.Exception) {}
 }

 open fun testTryWithResouceOnStaticField() {
  try {
   var `$primaryExc`: kotlin.Throwable? = null
   var `$resource`: trycatch.TryCatch.ClosableThing? = null
   try {
    `$resource` = trycatch.TryCatch.closableThing
    throw kotlin.Exception()
   } catch (`$exceptionFromTry`: kotlin.Throwable) {
    `$primaryExc` = `$exceptionFromTry`
    throw `$exceptionFromTry`!!
   } finally {
    `$primaryExc` = javaemul.internal.Exceptions.safeClose(`$resource`, `$primaryExc`)
    if (`$primaryExc` !== null) throw `$primaryExc`!!
   }
  } catch (e: kotlin.Exception) {}
 }

 open fun testNestedTryCatch() {
  try {
   throw kotlin.Exception()
  } catch (ae: kotlin.Exception) {
   try {
    throw kotlin.Exception()
   } catch (ie: kotlin.Exception) {}
  }
 }

 open fun testThrowGenerics() {
  throw this.getT<kotlin.Exception?>(kotlin.Exception())!!
 }

 fun <T> getT(t: T?): T? {
  return t
 }

 open fun testThrowBoundGenerics() {
  throw this.getThrowable<kotlin.Throwable?>()!!
 }

 fun <T: kotlin.Throwable?> getThrowable(): T? {
  return null
 }

 companion object {
  @kotlin.jvm.JvmField val closableThing: trycatch.TryCatch.ClosableThing? = trycatch.TryCatch.ClosableThing()
 }

 open class ClosableThing: java.lang.AutoCloseable {
  open override fun close() {}
 }
}
